RAW_REVIEWS_PARQUET_PATH = "data/rawreviews/"
DAILY_REVIEWS_PARQUET_PATH = "data/reviews/"
META_PARQUET_PATH = "data/meta/"
DB_PATH = "data/database.db"
MODEL_PATH = "data/model"
LOGGING_PATH = "data/logs/"
